# Generated by Django 3.2 on 2021-04-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('modelno', models.CharField(blank=True, max_length=50, null=True)),
                ('water', models.CharField(blank=True, max_length=50, null=True)),
                ('gas', models.CharField(blank=True, max_length=50, null=True)),
                ('air', models.CharField(blank=True, max_length=50, null=True)),
                ('wpf', models.CharField(blank=True, max_length=50, null=True)),
                ('density', models.CharField(blank=True, max_length=50, null=True)),
                ('vescosity', models.CharField(blank=True, max_length=50, null=True)),
                ('temp', models.CharField(blank=True, max_length=50, null=True)),
                ('pressure', models.CharField(blank=True, max_length=50, null=True)),
                ('distance', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
